# Generated by Django 4.2 on 2023-04-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.IntegerField(db_index=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['campaign', 'timestamp'], name='click_logs__campaig_8165fb_idx'),
        ),
    ]
